version: '3.8'

services:
  moodmorph:
    build:
      context: .
      dockerfile: Dockerfile.combined
    container_name: moodmorph
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - /app/frontend/node_modules
    networks:
      - moodmorph-network
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 400M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  moodmorph-network:
    driver: bridge
