version: '3.8'

services:
  moodmorph-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: moodmorph-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - moodmorph-network
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  moodmorph-network:
    driver: bridge
