version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    working_dir: /app/backend
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    working_dir: /app/frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=production
