version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: moodmorph-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - moodmorph-network
    volumes:
      - /tmp:/tmp

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: moodmorph-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - moodmorph-network

networks:
  moodmorph-network:
    driver: bridge
